# Generated by Django 5.2 on 2025-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
